server:
  port: 8051
  servlet:
    context-path: /api/v1
#spring configuration
spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/library
  h2:
    console:
      enabled: true
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql



