server:
  port: 8051
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/LibraryDB
    username: postgres
    password: 12345
  h2:
    console:
      enabled: true
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
